#!/bin/bash

modules="gconf ext types dag taskdep dagutils filepath filetype modname hier filesystem expr pp utils helper process findlibConf prog dependencies target project meta dist analyze sdist doc configure install prepare buildprogs build init exception help obuild"
libs="unix"
OCAMLOPT="ocamlopt.opt -g"

set -e 
time (cd src;
	rm -f *.cmi *.cmx *.o
	for mod in $modules
	do
		echo "COMPILING $mod"
		$OCAMLOPT -c ${mod}.ml
	done;
	echo "LINKING obuild.bootstrap"
	$OCAMLOPT -o obuild.bootstrap ${libs// /.cmxa }.cmxa ${modules// /.cmx }.cmx
	rm *.cmi *.cmx *.o
	mv obuild.bootstrap ..
)
export OCAMLRUNPARAM=b
./obuild.bootstrap clean
./obuild.bootstrap configure
time ./obuild.bootstrap build
if [ -x dist/build/obuild/obuild ]; then
	rm obuild.bootstrap
fi
