#!/bin/bash

# useful for obuild developpers

export OCAMLOPT_DEV="ocamlopt.opt -g -annot"

./bootstrap

# install it in my PATH
ln -sf $PWD/dist/build/obuild/obuild ~/bin/obuild

# soft link .annot files so that Emacs' tuareg-mode can find them
rm -rf _build
mkdir _build
HERE=`pwd`
for f in `find . -name *.annot` ; do
    cd ${HERE}/_build ; ln -sf ../$f ./ ;
done
cd $HERE

# generate TAGS; FBR: remove it once I can use ocamlspot
otags $(find . -name *.ml) -o TAGS
